# Generated by Django 2.2.5 on 2022-07-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220705_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
