# Generated by Django 2.2.5 on 2022-07-09 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0009_auto_20220710_0042'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resercation',
            new_name='Reservation',
        ),
    ]
