# Generated by Django 2.2.5 on 2022-09-04 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20220904_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.OneToOneField(on_delete=80, related_name='list', to=settings.AUTH_USER_MODEL),
        ),
    ]
